apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webflux-ehcache-ingress
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: api.blupine.freeddns.org
    http:
      paths:
      - path: /app-ehcache
        pathType: Prefix
        backend:
          service:
            name: webflux-ehcache-service
            port:
              number: 80