apiVersion: v1
kind: Service
metadata:
  name: webflux-ehcache-service
  namespace: apps
  labels:
    app: webflux-ehcache-service
spec:
  selector:
    app: webflux-ehcache
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
